name: stagexl_bitmapfont
version: 0.5.0+1
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  xml: '>=3.4.0 <4.0.0'
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
